CREATE TABLE "users" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`user_id`	INTEGER NOT NULL UNIQUE,
	`timezone`	TEXT NOT NULL,
	`created_at`	INTEGER DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	INTEGER DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `guilds` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`guild_id`	INTEGER NOT NULL UNIQUE,
	`timezones`	TEXT,
	`created_at`	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);